version: '3.8'

services:
  forest:
    image: ubuntu:22.04
    volumes:
      - ./entrypoint.sh:/entrypoint.sh
      - /home/grads/sxk6394/results:/results
    entrypoint: /entrypoint.sh
    networks:
      - free5gc-compose_privnet
    restart: always

networks:
  free5gc-compose_privnet:
    external: true
