version: '3.8'

services:
  forest:
    image: ubuntu:22.04
    command: >
      sh -c "
      apt-get update &&
      apt-get install -y wget git curl python3 python3-pip python3.10-venv && 
      git clone https://github.com/sathiyajith/foREST.git &&
      git clone https://github.com/ashwin63/5g-Microservice-testing.git &&
      python3 -m venv /venv &&
      source /venv/bin/activate &&
      pip install allpairspy &&
      cd foREST &&
      pip install -r requirements.txt &&
      tail -f /dev/null
      "
    volumes:
      - /home/grads/sxk6394/results/forest:/results
    networks:
      - free5gc-compose_privnet
    restart: always

networks:
  free5gc-compose_privnet:
    external: true
