version: '3.8'

services:
  restler:
    image: restler:latest
    entrypoint: ["sh", "-c", "while true; do echo 'Container is running'; sleep 60; done"]
    networks:
      - privnet
    restart: always
    volumes:
      - ./restler_files:/RESTler/restler/restler_files
networks:
  privnet:
    driver: bridge
