version: '3.8'

services:
  restler:
    image: restler:latest
    command: >
      sh -c "
      apk add git &&
      git clone https://github.com/ashwin63/5g-Microservice-testing.git &&
      tail -f /dev/null
      "
    networks:
      - privnet
    restart: always
    volumes:
      - /home/grads/sxk6394/results/restler:/results
networks:
  privnet:
    driver: bridge
